# Site settings
title: Josh Machado
description: Astronomy PhD Student
# baseurl: "" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Josh Machado
user_description: I'm a first year astronomy PhD student at Ohio State University. I completed my bachelor's in physics at UConn in 2020. My research interests include molecular clouds, as well as galactic (and extragalactic) star formation). I'm also interested in virtually any application of radio and millimeter astronomy.
user_title: Astronomy PhD Student
email: machado.35@osu.edu
twitter_username: astronomerjosh
github_username: joshmachado
# gplus_username:  lorem_ipsum

exclude: ['package.json', 'src' , 'node_modules']
